//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityServerInterfaces
{
    [Serializable]
    public class Int16ArrayMsg : Message
    {
        public const string k_RosMessageName = "unity_server_interfaces/Int16Array";
        public override string RosMessageName => k_RosMessageName;

        public short[] data;

        public Int16ArrayMsg()
        {
            this.data = new short[0];
        }

        public Int16ArrayMsg(short[] data)
        {
            this.data = data;
        }

        public static Int16ArrayMsg Deserialize(MessageDeserializer deserializer) => new Int16ArrayMsg(deserializer);

        private Int16ArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data, sizeof(short), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "Int16ArrayMsg: " +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
