//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityServerInterfaces
{
    [Serializable]
    public class NodeInfoMsg : Message
    {
        public const string k_RosMessageName = "unity_server_interfaces/NodeInfo";
        public override string RosMessageName => k_RosMessageName;

        public string name;

        public NodeInfoMsg()
        {
            this.name = "";
        }

        public NodeInfoMsg(string name)
        {
            this.name = name;
        }

        public static NodeInfoMsg Deserialize(MessageDeserializer deserializer) => new NodeInfoMsg(deserializer);

        private NodeInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "NodeInfoMsg: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
