//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityServerInterfaces
{
    [Serializable]
    public class NodeInfoArrayMsg : Message
    {
        public const string k_RosMessageName = "unity_server_interfaces/NodeInfoArray";
        public override string RosMessageName => k_RosMessageName;

        public NodeInfoMsg[] nodes;

        public NodeInfoArrayMsg()
        {
            this.nodes = new NodeInfoMsg[0];
        }

        public NodeInfoArrayMsg(NodeInfoMsg[] nodes)
        {
            this.nodes = nodes;
        }

        public static NodeInfoArrayMsg Deserialize(MessageDeserializer deserializer) => new NodeInfoArrayMsg(deserializer);

        private NodeInfoArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.nodes, NodeInfoMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.nodes);
            serializer.Write(this.nodes);
        }

        public override string ToString()
        {
            return "NodeInfoArrayMsg: " +
            "\nnodes: " + System.String.Join(", ", nodes.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
