//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityServerInterfaces
{
    [Serializable]
    public class PoseStampedOwnMsg : Message
    {
        public const string k_RosMessageName = "unity_server_interfaces/PoseStampedOwn";
        public override string RosMessageName => k_RosMessageName;

        public short transaction_id;
        public Geometry.PoseStampedMsg pose;

        public PoseStampedOwnMsg()
        {
            this.transaction_id = 0;
            this.pose = new Geometry.PoseStampedMsg();
        }

        public PoseStampedOwnMsg(short transaction_id, Geometry.PoseStampedMsg pose)
        {
            this.transaction_id = transaction_id;
            this.pose = pose;
        }

        public static PoseStampedOwnMsg Deserialize(MessageDeserializer deserializer) => new PoseStampedOwnMsg(deserializer);

        private PoseStampedOwnMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.transaction_id);
            this.pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.transaction_id);
            serializer.Write(this.pose);
        }

        public override string ToString()
        {
            return "PoseStampedOwnMsg: " +
            "\ntransaction_id: " + transaction_id.ToString() +
            "\npose: " + pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
