//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityServerInterfaces
{
    [Serializable]
    public class RobotArrayMsg : Message
    {
        public const string k_RosMessageName = "unity_server_interfaces/RobotArray";
        public override string RosMessageName => k_RosMessageName;

        public RobotMsg[] robots;

        public RobotArrayMsg()
        {
            this.robots = new RobotMsg[0];
        }

        public RobotArrayMsg(RobotMsg[] robots)
        {
            this.robots = robots;
        }

        public static RobotArrayMsg Deserialize(MessageDeserializer deserializer) => new RobotArrayMsg(deserializer);

        private RobotArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robots, RobotMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.robots);
            serializer.Write(this.robots);
        }

        public override string ToString()
        {
            return "RobotArrayMsg: " +
            "\nrobots: " + System.String.Join(", ", robots.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
