//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityServerInterfaces
{
    [Serializable]
    public class RobotMsg : Message
    {
        public const string k_RosMessageName = "unity_server_interfaces/Robot";
        public override string RosMessageName => k_RosMessageName;

        public string id;
        public string[] topics;
        public long confidence;

        public RobotMsg()
        {
            this.id = "";
            this.topics = new string[0];
            this.confidence = 0;
        }

        public RobotMsg(string id, string[] topics, long confidence)
        {
            this.id = id;
            this.topics = topics;
            this.confidence = confidence;
        }

        public static RobotMsg Deserialize(MessageDeserializer deserializer) => new RobotMsg(deserializer);

        private RobotMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.topics, deserializer.ReadLength());
            deserializer.Read(out this.confidence);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.WriteLength(this.topics);
            serializer.Write(this.topics);
            serializer.Write(this.confidence);
        }

        public override string ToString()
        {
            return "RobotMsg: " +
            "\nid: " + id.ToString() +
            "\ntopics: " + System.String.Join(", ", topics.ToList()) +
            "\nconfidence: " + confidence.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
