//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityServerInterfaces
{
    [Serializable]
    public class TFStaticArrayMsg : Message
    {
        public const string k_RosMessageName = "unity_server_interfaces/TFStaticArray";
        public override string RosMessageName => k_RosMessageName;

        public TFStaticMsg[] tf;

        public TFStaticArrayMsg()
        {
            this.tf = new TFStaticMsg[0];
        }

        public TFStaticArrayMsg(TFStaticMsg[] tf)
        {
            this.tf = tf;
        }

        public static TFStaticArrayMsg Deserialize(MessageDeserializer deserializer) => new TFStaticArrayMsg(deserializer);

        private TFStaticArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.tf, TFStaticMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.tf);
            serializer.Write(this.tf);
        }

        public override string ToString()
        {
            return "TFStaticArrayMsg: " +
            "\ntf: " + System.String.Join(", ", tf.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
