//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityServerInterfaces
{
    [Serializable]
    public class TFStaticMsg : Message
    {
        public const string k_RosMessageName = "unity_server_interfaces/TFStatic";
        public override string RosMessageName => k_RosMessageName;

        public string topic;
        public Geometry.TransformStampedMsg[] transforms;

        public TFStaticMsg()
        {
            this.topic = "";
            this.transforms = new Geometry.TransformStampedMsg[0];
        }

        public TFStaticMsg(string topic, Geometry.TransformStampedMsg[] transforms)
        {
            this.topic = topic;
            this.transforms = transforms;
        }

        public static TFStaticMsg Deserialize(MessageDeserializer deserializer) => new TFStaticMsg(deserializer);

        private TFStaticMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.topic);
            deserializer.Read(out this.transforms, Geometry.TransformStampedMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.topic);
            serializer.WriteLength(this.transforms);
            serializer.Write(this.transforms);
        }

        public override string ToString()
        {
            return "TFStaticMsg: " +
            "\ntopic: " + topic.ToString() +
            "\ntransforms: " + System.String.Join(", ", transforms.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
