//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityServerInterfaces
{
    [Serializable]
    public class TopicInfoMsg : Message
    {
        public const string k_RosMessageName = "unity_server_interfaces/TopicInfo";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public string[] types;

        public TopicInfoMsg()
        {
            this.name = "";
            this.types = new string[0];
        }

        public TopicInfoMsg(string name, string[] types)
        {
            this.name = name;
            this.types = types;
        }

        public static TopicInfoMsg Deserialize(MessageDeserializer deserializer) => new TopicInfoMsg(deserializer);

        private TopicInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.types, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.WriteLength(this.types);
            serializer.Write(this.types);
        }

        public override string ToString()
        {
            return "TopicInfoMsg: " +
            "\nname: " + name.ToString() +
            "\ntypes: " + System.String.Join(", ", types.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
