//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityServerInterfaces
{
    [Serializable]
    public class TopicInfoArrayMsg : Message
    {
        public const string k_RosMessageName = "unity_server_interfaces/TopicInfoArray";
        public override string RosMessageName => k_RosMessageName;

        public TopicInfoMsg[] topics;

        public TopicInfoArrayMsg()
        {
            this.topics = new TopicInfoMsg[0];
        }

        public TopicInfoArrayMsg(TopicInfoMsg[] topics)
        {
            this.topics = topics;
        }

        public static TopicInfoArrayMsg Deserialize(MessageDeserializer deserializer) => new TopicInfoArrayMsg(deserializer);

        private TopicInfoArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.topics, TopicInfoMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.topics);
            serializer.Write(this.topics);
        }

        public override string ToString()
        {
            return "TopicInfoArrayMsg: " +
            "\ntopics: " + System.String.Join(", ", topics.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
