//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityServerInterfaces
{
    [Serializable]
    public class RobotListSrvRequest : Message
    {
        public const string k_RosMessageName = "unity_server_interfaces/RobotListSrv";
        public override string RosMessageName => k_RosMessageName;

        public bool request;

        public RobotListSrvRequest()
        {
            this.request = false;
        }

        public RobotListSrvRequest(bool request)
        {
            this.request = request;
        }

        public static RobotListSrvRequest Deserialize(MessageDeserializer deserializer) => new RobotListSrvRequest(deserializer);

        private RobotListSrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.request);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request);
        }

        public override string ToString()
        {
            return "RobotListSrvRequest: " +
            "\nrequest: " + request.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
