//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityServerInterfaces
{
    [Serializable]
    public class RobotListSrvResponse : Message
    {
        public const string k_RosMessageName = "unity_server_interfaces/RobotListSrv";
        public override string RosMessageName => k_RosMessageName;

        public string[] robot_names;

        public RobotListSrvResponse()
        {
            this.robot_names = new string[0];
        }

        public RobotListSrvResponse(string[] robot_names)
        {
            this.robot_names = robot_names;
        }

        public static RobotListSrvResponse Deserialize(MessageDeserializer deserializer) => new RobotListSrvResponse(deserializer);

        private RobotListSrvResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robot_names, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.robot_names);
            serializer.Write(this.robot_names);
        }

        public override string ToString()
        {
            return "RobotListSrvResponse: " +
            "\nrobot_names: " + System.String.Join(", ", robot_names.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
